### ISSUE TITLE
Unused Code

### ISSUE THREAD

**Issue by averybackus** [adriansd1/EECS-2311-Software-Development-Project#17]
Reported by: Avery Backus
Date reported: 2024-03-24
Report type: coding
Can reproduce: yes
Severity: Minor
Priority: Minor
Problem summary: Code with no usages / only used in test classes.
Key words: No usages, unused
Problem description: Many classes such as Food, FoodAndQuantity, FoodMenu, Kitchen, Order, and PaymentHandler have methods or fields with no usages or only usages in their respective test classes. Unless these methods and fields will be used in future versions, they should be removed.
Suggested fix: each developer should review their code and remove anything unnecessary.
Status: open
Resolution: pending

**Comment by adriansd1** [comment]
Avery refactored and removed unnecessary code
